// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace JdhPro.Tests.E2E.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class BlogListingPageFeature : object, global::Xunit.IClassFixture<BlogListingPageFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en"), "Features", "Blog Listing Page", "  As a visitor\r\n  I want to view the blog listing page\r\n  So that I can see all a" +
                "vailable blog posts", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "BlogListing.feature"
#line hidden
        
        public BlogListingPageFeature(BlogListingPageFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/BlogListing.feature.ndjson", 10);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Blog listing page loads successfully")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Blog Listing Page")]
        [global::Xunit.TraitAttribute("Description", "Blog listing page loads successfully")]
        [global::Xunit.TraitAttribute("Category", "future")]
        [global::Xunit.TraitAttribute("Category", "blog")]
        public async global::System.Threading.Tasks.Task BlogListingPageLoadsSuccessfully()
        {
            string[] tagsOfScenario = new string[] {
                    "future",
                    "blog"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Blog listing page loads successfully", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 10
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
  await testRunner.WhenAsync("I navigate to the blog page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 12
  await testRunner.ThenAsync("I should see the page title \"TECHNICAL.INSIGHTS\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 13
  await testRunner.AndAsync("the page should display blog posts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Blog posts are displayed from posts.json", Skip="Ignored")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Blog Listing Page")]
        [global::Xunit.TraitAttribute("Description", "Blog posts are displayed from posts.json")]
        [global::Xunit.TraitAttribute("Category", "future")]
        [global::Xunit.TraitAttribute("Category", "blog")]
        [global::Xunit.TraitAttribute("Category", "future")]
        [global::Xunit.TraitAttribute("Category", "blog")]
        public async global::System.Threading.Tasks.Task BlogPostsAreDisplayedFromPosts_Json()
        {
            string[] tagsOfScenario = new string[] {
                    "future",
                    "blog",
                    "ignore",
                    "future",
                    "blog"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Blog posts are displayed from posts.json", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 16
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 17
  await testRunner.GivenAsync("blog syndication has completed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 18
  await testRunner.WhenAsync("I navigate to the blog page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
  await testRunner.ThenAsync("I should see blog post cards", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 20
  await testRunner.AndAsync("each post should display a title", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
  await testRunner.AndAsync("each post should display a date", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
  await testRunner.AndAsync("each post should display categories", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Blog posts link to detail pages", Skip="Ignored")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Blog Listing Page")]
        [global::Xunit.TraitAttribute("Description", "Blog posts link to detail pages")]
        [global::Xunit.TraitAttribute("Category", "future")]
        [global::Xunit.TraitAttribute("Category", "blog")]
        [global::Xunit.TraitAttribute("Category", "future")]
        [global::Xunit.TraitAttribute("Category", "blog")]
        public async global::System.Threading.Tasks.Task BlogPostsLinkToDetailPages()
        {
            string[] tagsOfScenario = new string[] {
                    "future",
                    "blog",
                    "ignore",
                    "future",
                    "blog"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Blog posts link to detail pages", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 25
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 26
  await testRunner.GivenAsync("blog syndication has completed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 27
  await testRunner.WhenAsync("I navigate to the blog page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 28
  await testRunner.AndAsync("I click on a blog post", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 29
  await testRunner.ThenAsync("I should navigate to the post detail page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Blog posts are sorted by date")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Blog Listing Page")]
        [global::Xunit.TraitAttribute("Description", "Blog posts are sorted by date")]
        [global::Xunit.TraitAttribute("Category", "future")]
        [global::Xunit.TraitAttribute("Category", "blog")]
        public async global::System.Threading.Tasks.Task BlogPostsAreSortedByDate()
        {
            string[] tagsOfScenario = new string[] {
                    "future",
                    "blog"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Blog posts are sorted by date", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 32
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 33
  await testRunner.GivenAsync("blog syndication has completed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 34
  await testRunner.WhenAsync("I navigate to the blog page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 35
  await testRunner.ThenAsync("posts should be displayed in date order (newest first)", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Blog posts display metadata", Skip="Ignored")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Blog Listing Page")]
        [global::Xunit.TraitAttribute("Description", "Blog posts display metadata")]
        [global::Xunit.TraitAttribute("Category", "future")]
        [global::Xunit.TraitAttribute("Category", "blog")]
        [global::Xunit.TraitAttribute("Category", "future")]
        [global::Xunit.TraitAttribute("Category", "blog")]
        public async global::System.Threading.Tasks.Task BlogPostsDisplayMetadata()
        {
            string[] tagsOfScenario = new string[] {
                    "future",
                    "blog",
                    "ignore",
                    "future",
                    "blog"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Blog posts display metadata", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 38
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 39
  await testRunner.GivenAsync("blog syndication has completed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 40
  await testRunner.WhenAsync("I navigate to the blog page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 41
  await testRunner.ThenAsync("each post should show the publish date", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 42
  await testRunner.AndAsync("each post should show categories", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 43
  await testRunner.AndAsync("each post should show tags (if available)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Filter blog posts by category")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Blog Listing Page")]
        [global::Xunit.TraitAttribute("Description", "Filter blog posts by category")]
        [global::Xunit.TraitAttribute("Category", "future")]
        [global::Xunit.TraitAttribute("Category", "blog")]
        public async global::System.Threading.Tasks.Task FilterBlogPostsByCategory()
        {
            string[] tagsOfScenario = new string[] {
                    "future",
                    "blog"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Filter blog posts by category", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 46
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 47
  await testRunner.GivenAsync("blog syndication has completed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 48
  await testRunner.WhenAsync("I navigate to the blog page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 49
  await testRunner.AndAsync("I filter by \"Technical\" category", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 50
  await testRunner.ThenAsync("only posts in \"Technical\" category should be shown", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Search blog posts", Skip="Ignored")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Blog Listing Page")]
        [global::Xunit.TraitAttribute("Description", "Search blog posts")]
        [global::Xunit.TraitAttribute("Category", "future")]
        [global::Xunit.TraitAttribute("Category", "blog")]
        [global::Xunit.TraitAttribute("Category", "future")]
        [global::Xunit.TraitAttribute("Category", "blog")]
        public async global::System.Threading.Tasks.Task SearchBlogPosts()
        {
            string[] tagsOfScenario = new string[] {
                    "future",
                    "blog",
                    "ignore",
                    "future",
                    "blog"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Search blog posts", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 53
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 54
  await testRunner.GivenAsync("blog syndication has completed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 55
  await testRunner.WhenAsync("I navigate to the blog page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 56
  await testRunner.AndAsync("I search for \"testing\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 57
  await testRunner.ThenAsync("only posts containing \"testing\" should be shown", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Pagination works correctly", Skip="Ignored")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Blog Listing Page")]
        [global::Xunit.TraitAttribute("Description", "Pagination works correctly")]
        [global::Xunit.TraitAttribute("Category", "future")]
        [global::Xunit.TraitAttribute("Category", "blog")]
        [global::Xunit.TraitAttribute("Category", "future")]
        [global::Xunit.TraitAttribute("Category", "blog")]
        public async global::System.Threading.Tasks.Task PaginationWorksCorrectly()
        {
            string[] tagsOfScenario = new string[] {
                    "future",
                    "blog",
                    "ignore",
                    "future",
                    "blog"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Pagination works correctly", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 60
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 61
  await testRunner.GivenAsync("blog syndication has completed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 62
  await testRunner.AndAsync("there are more than 5 posts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 63
  await testRunner.WhenAsync("I navigate to the blog page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 64
  await testRunner.ThenAsync("I should see pagination controls", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 65
  await testRunner.AndAsync("I should see up to 10 posts per page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 66
  await testRunner.WhenAsync("I click next page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 67
  await testRunner.ThenAsync("I should see the next set of posts", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await BlogListingPageFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await BlogListingPageFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
