// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace JdhPro.Tests.E2E.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class BlogPostDetailPageFeature : object, global::Xunit.IClassFixture<BlogPostDetailPageFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en"), "Features", "Blog Post Detail Page", "  As a visitor\r\n  I want to read individual blog posts\r\n  So that I can learn fro" +
                "m the technical content", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "BlogPost.feature"
#line hidden
        
        public BlogPostDetailPageFeature(BlogPostDetailPageFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/BlogPost.feature.ndjson", 13);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Blog post detail page loads successfully")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Blog Post Detail Page")]
        [global::Xunit.TraitAttribute("Description", "Blog post detail page loads successfully")]
        [global::Xunit.TraitAttribute("Category", "future")]
        [global::Xunit.TraitAttribute("Category", "blog")]
        public async global::System.Threading.Tasks.Task BlogPostDetailPageLoadsSuccessfully()
        {
            string[] tagsOfScenario = new string[] {
                    "future",
                    "blog"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Blog post detail page loads successfully", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 10
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
  await testRunner.GivenAsync("blog syndication has completed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 12
  await testRunner.WhenAsync("I navigate to a blog post detail page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 13
  await testRunner.ThenAsync("I should see the post title", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 14
  await testRunner.AndAsync("I should see the post content", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
  await testRunner.AndAsync("I should see the post metadata", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Blog post displays full content")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Blog Post Detail Page")]
        [global::Xunit.TraitAttribute("Description", "Blog post displays full content")]
        [global::Xunit.TraitAttribute("Category", "future")]
        [global::Xunit.TraitAttribute("Category", "blog")]
        public async global::System.Threading.Tasks.Task BlogPostDisplaysFullContent()
        {
            string[] tagsOfScenario = new string[] {
                    "future",
                    "blog"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Blog post displays full content", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 18
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 19
  await testRunner.GivenAsync("blog syndication has completed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 20
  await testRunner.WhenAsync("I navigate to a blog post detail page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 21
  await testRunner.ThenAsync("the post HTML content should be rendered", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 22
  await testRunner.AndAsync("the content should be properly formatted", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
  await testRunner.AndAsync("code blocks should be syntax highlighted", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Blog post displays metadata")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Blog Post Detail Page")]
        [global::Xunit.TraitAttribute("Description", "Blog post displays metadata")]
        [global::Xunit.TraitAttribute("Category", "future")]
        [global::Xunit.TraitAttribute("Category", "blog")]
        public async global::System.Threading.Tasks.Task BlogPostDisplaysMetadata()
        {
            string[] tagsOfScenario = new string[] {
                    "future",
                    "blog"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Blog post displays metadata", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 26
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 27
  await testRunner.GivenAsync("blog syndication has completed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 28
  await testRunner.WhenAsync("I navigate to a blog post detail page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 29
  await testRunner.ThenAsync("I should see the publish date", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 30
  await testRunner.AndAsync("I should see the author name", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 31
  await testRunner.AndAsync("I should see the categories", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
  await testRunner.AndAsync("I should see the tags", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Syndicated posts display canonical URL")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Blog Post Detail Page")]
        [global::Xunit.TraitAttribute("Description", "Syndicated posts display canonical URL")]
        [global::Xunit.TraitAttribute("Category", "future")]
        [global::Xunit.TraitAttribute("Category", "blog")]
        public async global::System.Threading.Tasks.Task SyndicatedPostsDisplayCanonicalURL()
        {
            string[] tagsOfScenario = new string[] {
                    "future",
                    "blog"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Syndicated posts display canonical URL", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 35
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 36
  await testRunner.GivenAsync("blog syndication has completed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 37
  await testRunner.WhenAsync("I navigate to a syndicated blog post", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 38
  await testRunner.ThenAsync("I should see a canonical URL link", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 39
  await testRunner.AndAsync("the canonical link should point to the original post", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Blog post has proper meta tags for SEO")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Blog Post Detail Page")]
        [global::Xunit.TraitAttribute("Description", "Blog post has proper meta tags for SEO")]
        [global::Xunit.TraitAttribute("Category", "future")]
        [global::Xunit.TraitAttribute("Category", "blog")]
        public async global::System.Threading.Tasks.Task BlogPostHasProperMetaTagsForSEO()
        {
            string[] tagsOfScenario = new string[] {
                    "future",
                    "blog"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Blog post has proper meta tags for SEO", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 42
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 43
  await testRunner.GivenAsync("blog syndication has completed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 44
  await testRunner.WhenAsync("I navigate to a blog post detail page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 45
  await testRunner.ThenAsync("the page should have a title meta tag", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 46
  await testRunner.AndAsync("the page should have a description meta tag", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 47
  await testRunner.AndAsync("the page should have Open Graph meta tags", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Blog post has table of contents")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Blog Post Detail Page")]
        [global::Xunit.TraitAttribute("Description", "Blog post has table of contents")]
        [global::Xunit.TraitAttribute("Category", "future")]
        [global::Xunit.TraitAttribute("Category", "blog")]
        public async global::System.Threading.Tasks.Task BlogPostHasTableOfContents()
        {
            string[] tagsOfScenario = new string[] {
                    "future",
                    "blog"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Blog post has table of contents", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 50
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 51
  await testRunner.GivenAsync("blog syndication has completed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 52
  await testRunner.AndAsync("the post has UseToc enabled", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 53
  await testRunner.WhenAsync("I navigate to the blog post detail page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 54
  await testRunner.ThenAsync("I should see a table of contents", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 55
  await testRunner.AndAsync("clicking TOC links should scroll to sections", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Navigate between blog posts")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Blog Post Detail Page")]
        [global::Xunit.TraitAttribute("Description", "Navigate between blog posts")]
        [global::Xunit.TraitAttribute("Category", "future")]
        [global::Xunit.TraitAttribute("Category", "blog")]
        public async global::System.Threading.Tasks.Task NavigateBetweenBlogPosts()
        {
            string[] tagsOfScenario = new string[] {
                    "future",
                    "blog"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Navigate between blog posts", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 58
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 59
  await testRunner.GivenAsync("blog syndication has completed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 60
  await testRunner.WhenAsync("I navigate to a blog post detail page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 61
  await testRunner.ThenAsync("I should see a \"Previous Post\" link (if available)", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 62
  await testRunner.AndAsync("I should see a \"Next Post\" link (if available)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 63
  await testRunner.WhenAsync("I click \"Next Post\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 64
  await testRunner.ThenAsync("I should navigate to the next blog post", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Blog post URL uses slug")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Blog Post Detail Page")]
        [global::Xunit.TraitAttribute("Description", "Blog post URL uses slug")]
        [global::Xunit.TraitAttribute("Category", "future")]
        [global::Xunit.TraitAttribute("Category", "blog")]
        public async global::System.Threading.Tasks.Task BlogPostURLUsesSlug()
        {
            string[] tagsOfScenario = new string[] {
                    "future",
                    "blog"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Blog post URL uses slug", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 67
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 68
  await testRunner.GivenAsync("blog syndication has completed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 69
  await testRunner.WhenAsync("I navigate to a blog post detail page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 70
  await testRunner.ThenAsync("the URL should contain the post slug", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 71
  await testRunner.AndAsync("the slug should be URL-friendly", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Blog post displays reading time")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Blog Post Detail Page")]
        [global::Xunit.TraitAttribute("Description", "Blog post displays reading time")]
        [global::Xunit.TraitAttribute("Category", "future")]
        [global::Xunit.TraitAttribute("Category", "blog")]
        public async global::System.Threading.Tasks.Task BlogPostDisplaysReadingTime()
        {
            string[] tagsOfScenario = new string[] {
                    "future",
                    "blog"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Blog post displays reading time", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 74
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 75
  await testRunner.GivenAsync("blog syndication has completed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 76
  await testRunner.WhenAsync("I navigate to a blog post detail page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 77
  await testRunner.ThenAsync("I should see the estimated reading time", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 78
  await testRunner.AndAsync("the reading time should be calculated from word count", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Related posts are displayed")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Blog Post Detail Page")]
        [global::Xunit.TraitAttribute("Description", "Related posts are displayed")]
        [global::Xunit.TraitAttribute("Category", "future")]
        [global::Xunit.TraitAttribute("Category", "blog")]
        public async global::System.Threading.Tasks.Task RelatedPostsAreDisplayed()
        {
            string[] tagsOfScenario = new string[] {
                    "future",
                    "blog"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Related posts are displayed", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 81
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 82
  await testRunner.GivenAsync("blog syndication has completed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 83
  await testRunner.WhenAsync("I navigate to a blog post detail page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 84
  await testRunner.ThenAsync("I should see related posts section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 85
  await testRunner.AndAsync("related posts should share categories or tags", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Code snippets are properly formatted")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Blog Post Detail Page")]
        [global::Xunit.TraitAttribute("Description", "Code snippets are properly formatted")]
        [global::Xunit.TraitAttribute("Category", "future")]
        [global::Xunit.TraitAttribute("Category", "blog")]
        public async global::System.Threading.Tasks.Task CodeSnippetsAreProperlyFormatted()
        {
            string[] tagsOfScenario = new string[] {
                    "future",
                    "blog"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Code snippets are properly formatted", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 88
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 89
  await testRunner.GivenAsync("blog syndication has completed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 90
  await testRunner.AndAsync("the post contains code snippets", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 91
  await testRunner.WhenAsync("I navigate to the blog post detail page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 92
  await testRunner.ThenAsync("code blocks should have syntax highlighting", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 93
  await testRunner.AndAsync("code blocks should have copy buttons", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 94
  await testRunner.AndAsync("code blocks should display the language", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await BlogPostDetailPageFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await BlogPostDetailPageFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
